### ISSUE TITLE
compilation issue line 106

### ISSUE THREAD

**Issue by Incog-Makes** [augustgl/screamIRC#1]
Got it open in VS and tried compiling, got an error of "argument of type "TCHAR *" is incompatible with parameter of type "char *" "
line 106.

Is this just a me thing or are you able to replicate it on your side too?

**Comment by augustgl** [comment]
Are you compiling for Unicode or ANSI charset

**Comment by Incog-Makes** [comment]
good question, I'm not entirely sure which one and I can't seem to find a way off google, what would be a way of checking/changing to the right one?

**Comment by Incog-Makes** [comment]
ah sorry, unicode.

https://prnt.sc/10apthb

**Comment by augustgl** [comment]
This project was designed for ANSI (not wide char) so you should be able to go into properties in visual studio, and change the character set.

project properities -> configuration properities -> general -> charater set

Change to "not set"

Please note that this was written in visual studio. I cannot say if it will work in mingw or something else. 

If the error persists please get back to me :)

**Comment by Incog-Makes** [comment]
Yup just was about to post haha, switched it to not set and compiled fine, thanks for you help! :)

**Comment by augustgl** [comment]
No problem 🤝
